In [9]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

## Pre-Processing

In [17]:
# PARAMS:
descFile = "descriptor.json"
inputFile = "foursquare.csv"

df = pd.read_csv(inputFile)
df.head(5)

,checkin_id,venue_id,tid,lat_lon,date_time,time,day,poi,type,root_type,price,rating,weather,label
0,283468,4eba3331722edc0eaf1762bb,126,40.8331652006224 -73.9418603427692,2012-11-12 05:17:18,317,Monday,The Lair Of Modern Strange Cowboy,Home (private),Residence,-1,-1.0,Clear,6
1,284212,4fe9524ce4b0d971aa120f82,126,40.8340978041072 -73.9452672225881,2012-11-12 23:24:55,1404,Monday,Galaxy Gourmet Deli,Deli / Bodega,Food,1,8.2,Clouds,6
2,284225,4eba3331722edc0eaf1762bb,126,40.8331652006224 -73.9418603427692,2012-11-13 00:00:07,0,Tuesday,The Lair Of Modern Strange Cowboy,Home (private),Residence,-1,-1.0,Clouds,6
3,284771,4d5febf914963704def9dd94,126,40.7646959283254 -73.8851974964414,2012-11-15 17:49:01,1069,Thursday,Popeyes Louisiana Kitchen,Fried Chicken Joint,Food,3,6.6,Clear,6
4,284821,4dd408046365c27b0dbf4239,126,40.7660790376824 -73.8835287094116,2012-11-15 18:40:16,1120,Thursday,MTA Bus Operations Depot - LaGuardia,Bus Station,Travel & Transport,-1,-1.0,Clear,6

In [23]:
# SELECT FEATURES:
df = df[[
    'label',
    'tid',
    'time',
    'day',
    'poi',
    'price',
    'rating',
    'weather'
]]
df.head(5)

   label                                   poi
0      6     The Lair Of Modern Strange Cowboy
1      6                   Galaxy Gourmet Deli
2      6     The Lair Of Modern Strange Cowboy
3      6             Popeyes Louisiana Kitchen
4      6  MTA Bus Operations Depot - LaGuardia

In [22]:
X_train, X_test = train_test_split(df, test_size=0.33, random_state=1)
X_train.to_csv(r'train_'+inputFile)
X_test.to_csv(r'test_'+inputFile)

## 1 - Wizard Run

In [ ]:


print("wizard", descFile, inputFile)
!command java -jar wizard $descFile $inputFile